-- Extend the canonical financial-report snapshot with Indonesian reporting
-- foundation data without creating a parallel reporting engine.
--
-- IMPORTANT:
-- - Selecting a framework is explicit. No report is automatically represented
--   as SAK compliant.
-- - All new data is version-bound and frozen with the published version.
-- - Investor reads continue to resolve through the exact published version.

alter type public.financial_statement add value if not exists 'changes_in_equity';

alter table public.financial_report_versions
  add column if not exists accounting_framework text,
  add column if not exists basis_of_preparation text;

alter table public.financial_report_versions
  drop constraint if exists financial_report_versions_accounting_framework_valid;

alter table public.financial_report_versions
  add constraint financial_report_versions_accounting_framework_valid
  check (accounting_framework is null or accounting_framework in ('sak_ep', 'sak_indonesia', 'other'));

comment on column public.financial_report_versions.accounting_framework is
  'Explicit accounting framework selected by management. Null means not declared; this column never implies compliance automatically.';
comment on column public.financial_report_versions.basis_of_preparation is
  'Version-bound basis of preparation disclosed to readers of the financial statements.';

create table if not exists public.financial_report_disclosures (
  id uuid primary key default gen_random_uuid(),
  financial_report_version_id uuid not null
    references public.financial_report_versions (id) on delete cascade,
  disclosure_key text not null,
  title text not null,
  content text not null,
  position integer not null default 0,
  created_at timestamptz not null default now(),

  constraint financial_report_disclosures_key_shape
    check (disclosure_key ~ '^[a-z][a-z0-9_]*$'),
  constraint financial_report_disclosures_title_not_blank
    check (length(btrim(title)) > 0),
  constraint financial_report_disclosures_content_not_blank
    check (length(btrim(content)) > 0),
  constraint financial_report_disclosures_unique
    unique (financial_report_version_id, disclosure_key)
);

create index if not exists financial_report_disclosures_version_idx
  on public.financial_report_disclosures (financial_report_version_id, position);

comment on table public.financial_report_disclosures is
  'Version-bound notes to the financial statements (CALK). Content is factual management/accounting disclosure and is never generated by the system.';

-- Reuse the canonical published-snapshot freeze semantics for CALK.
create or replace function app.guard_financial_report_disclosure()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_version_id uuid := coalesce(new.financial_report_version_id, old.financial_report_version_id);
  v_status public.publication_status;
begin
  select status into v_status
  from public.financial_report_versions
  where id = v_version_id;

  if v_status = 'published' then
    raise exception 'Disclosures belonging to a published financial report version cannot be changed.'
      using errcode = '42501';
  end if;

  return coalesce(new, old);
end;
$$;

create trigger financial_report_disclosures_guard
  before insert or update or delete on public.financial_report_disclosures
  for each row execute function app.guard_financial_report_disclosure();

alter table public.financial_report_disclosures enable row level security;
alter table public.financial_report_disclosures force row level security;

revoke all on public.financial_report_disclosures from anon, authenticated;
grant select on public.financial_report_disclosures to authenticated;

create policy financial_report_disclosures_select
  on public.financial_report_disclosures for select to authenticated
  using (
    exists (
      select 1
      from public.financial_report_versions v
      where v.id = financial_report_version_id
    )
  );

-- The new statement uses the existing equity category. Replace the original
-- category/statement check so changes-in-equity rows cannot be misclassified.
alter table public.financial_line_items
  drop constraint if exists financial_line_items_category_matches_statement;

alter table public.financial_line_items
  add constraint financial_line_items_category_matches_statement check (
    case statement
      when 'income' then category in ('revenue', 'expense')
      when 'balance' then category in ('asset', 'liability', 'equity')
      when 'cash_flow' then category in ('operating', 'investing', 'financing')
      when 'changes_in_equity' then category = 'equity'
    end
  );

-- Extended atomic writer. The legacy 4-argument function remains available for
-- compatibility; all new UI uses this version-bound writer.
create or replace function app.save_financial_report_draft_content(
  p_report_id uuid,
  p_document_asset_id uuid,
  p_line_items jsonb,
  p_kpis jsonb,
  p_accounting_framework text,
  p_basis_of_preparation text,
  p_disclosures jsonb
)
returns table(
  line_item_count integer,
  kpi_count integer,
  disclosure_count integer,
  document_asset_id uuid
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_report public.financial_reports%rowtype;
  v_version public.financial_report_versions%rowtype;
  v_period_status public.period_status;
begin
  if not app.has_permission('financial_reports.update') then
    raise exception 'Missing permission: financial_reports.update' using errcode = '42501';
  end if;

  if jsonb_typeof(coalesce(p_line_items, '[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_kpis, '[]'::jsonb)) <> 'array'
     or jsonb_typeof(coalesce(p_disclosures, '[]'::jsonb)) <> 'array' then
    raise exception 'Financial report content must be JSON arrays.' using errcode = '22023';
  end if;

  if jsonb_array_length(coalesce(p_line_items, '[]'::jsonb)) > 250
     or jsonb_array_length(coalesce(p_kpis, '[]'::jsonb)) > 100
     or jsonb_array_length(coalesce(p_disclosures, '[]'::jsonb)) > 100 then
    raise exception 'Financial report content exceeds the allowed size.' using errcode = '22023';
  end if;

  if p_accounting_framework is not null
     and p_accounting_framework not in ('sak_ep', 'sak_indonesia', 'other') then
    raise exception 'Unsupported accounting framework.' using errcode = '22023';
  end if;

  select * into v_report
  from public.financial_reports
  where id = p_report_id
  for update;

  if v_report.id is null or v_report.current_version_id is null then
    raise exception 'Financial report or current version not found.' using errcode = 'P0002';
  end if;

  select * into v_version
  from public.financial_report_versions
  where id = v_report.current_version_id
    and financial_report_id = v_report.id
  for update;

  if v_version.id is null then
    raise exception 'Current financial report version not found.' using errcode = 'P0002';
  end if;

  if v_report.status <> 'draft' or v_version.status <> 'draft' then
    raise exception 'Only draft financial reports can be edited.' using errcode = '42501';
  end if;

  select status into v_period_status
  from public.financial_periods
  where id = v_report.financial_period_id;

  if v_period_status = 'locked' then
    raise exception 'Locked financial periods cannot be edited.' using errcode = '42501';
  end if;

  if p_document_asset_id is not null and not exists (
    select 1
    from public.media_assets a
    where a.id = p_document_asset_id
      and a.finalized_at is not null
      and a.visibility = 'restricted'
      and a.bucket = 'financial-documents'
  ) then
    raise exception 'Financial report attachment is invalid.' using errcode = '23503';
  end if;

  delete from public.financial_line_items
  where financial_report_version_id = v_version.id;

  insert into public.financial_line_items (
    financial_report_version_id, statement, category, line_key, label,
    amount, currency, position, note
  )
  select
    v_version.id,
    item.statement::public.financial_statement,
    item.category::public.financial_category,
    btrim(item.line_key),
    btrim(item.label),
    item.amount,
    upper(btrim(item.currency)),
    item.position,
    nullif(btrim(coalesce(item.note, '')), '')
  from jsonb_to_recordset(coalesce(p_line_items, '[]'::jsonb)) as item(
    statement text,
    category text,
    line_key text,
    label text,
    amount numeric,
    currency text,
    position integer,
    note text
  );

  delete from public.financial_kpis
  where financial_report_version_id = v_version.id;

  insert into public.financial_kpis (
    financial_report_version_id, kpi_key, label, value, unit, basis, position
  )
  select
    v_version.id,
    btrim(item.kpi_key),
    btrim(item.label),
    item.value,
    btrim(item.unit),
    btrim(item.basis),
    item.position
  from jsonb_to_recordset(coalesce(p_kpis, '[]'::jsonb)) as item(
    kpi_key text,
    label text,
    value numeric,
    unit text,
    basis text,
    position integer
  );

  delete from public.financial_report_disclosures
  where financial_report_version_id = v_version.id;

  insert into public.financial_report_disclosures (
    financial_report_version_id, disclosure_key, title, content, position
  )
  select
    v_version.id,
    btrim(item.disclosure_key),
    btrim(item.title),
    btrim(item.content),
    item.position
  from jsonb_to_recordset(coalesce(p_disclosures, '[]'::jsonb)) as item(
    disclosure_key text,
    title text,
    content text,
    position integer
  );

  update public.financial_report_versions
  set document_asset_id = p_document_asset_id,
      accounting_framework = nullif(btrim(coalesce(p_accounting_framework, '')), ''),
      basis_of_preparation = nullif(btrim(coalesce(p_basis_of_preparation, '')), '')
  where id = v_version.id;

  update public.financial_reports
  set updated_at = now()
  where id = v_report.id;

  return query select
    jsonb_array_length(coalesce(p_line_items, '[]'::jsonb)),
    jsonb_array_length(coalesce(p_kpis, '[]'::jsonb)),
    jsonb_array_length(coalesce(p_disclosures, '[]'::jsonb)),
    p_document_asset_id;
end;
$$;

revoke all on function app.save_financial_report_draft_content(uuid,uuid,jsonb,jsonb,text,text,jsonb)
  from public, anon;
grant execute on function app.save_financial_report_draft_content(uuid,uuid,jsonb,jsonb,text,text,jsonb)
  to authenticated;

-- Preserve the existing lifecycle and period-finality guard, while adding
-- readiness requirements only when management explicitly declares a framework.
create or replace function app.transition_financial_report(
  p_report_id uuid,
  p_target public.publication_status
)
returns table(
  report_id uuid,
  version_id uuid,
  previous_status public.publication_status,
  status public.publication_status
)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_report public.financial_reports%rowtype;
  v_version public.financial_report_versions%rowtype;
  v_period_status public.period_status;
  v_period_end date;
  v_permission text;
  v_now timestamptz := now();
begin
  select * into v_report
  from public.financial_reports
  where id = p_report_id
  for update;

  if v_report.id is null then
    raise exception 'Financial report not found.' using errcode = 'P0002';
  end if;
  if v_report.current_version_id is null then
    raise exception 'Financial report has no current version.' using errcode = '23514';
  end if;

  select * into v_version
  from public.financial_report_versions
  where id = v_report.current_version_id
    and financial_report_id = v_report.id
  for update;

  if v_version.id is null then
    raise exception 'Current financial report version not found.' using errcode = 'P0002';
  end if;

  if v_report.status = 'draft' and p_target = 'review' then
    v_permission := 'financial_reports.review';

    if v_version.document_asset_id is null
       or not exists (
         select 1 from public.financial_line_items
         where financial_report_version_id = v_version.id
       )
       or not exists (
         select 1 from public.financial_kpis
         where financial_report_version_id = v_version.id
       ) then
      raise exception 'Add an attachment, financial line items, and KPIs before review.'
        using errcode = '23514';
    end if;

    if v_version.accounting_framework is not null then
      if nullif(btrim(coalesce(v_version.basis_of_preparation, '')), '') is null then
        raise exception 'Add the basis of preparation before reviewing a framework-declared report.'
          using errcode = '23514';
      end if;

      if not exists (
        select 1 from public.financial_line_items
        where financial_report_version_id = v_version.id
          and statement = 'changes_in_equity'
      ) then
        raise exception 'Add the statement of changes in equity before reviewing a framework-declared report.'
          using errcode = '23514';
      end if;

      if not exists (
        select 1 from public.financial_report_disclosures
        where financial_report_version_id = v_version.id
      ) then
        raise exception 'Add notes to the financial statements before reviewing a framework-declared report.'
          using errcode = '23514';
      end if;
    end if;
  elsif v_report.status = 'review' and p_target = 'approved' then
    v_permission := 'financial_reports.approve';
  elsif v_report.status = 'approved' and p_target = 'published' then
    v_permission := 'financial_reports.publish';

    select fp.status, fp.ends_on
      into v_period_status, v_period_end
    from public.financial_periods fp
    where fp.id = v_report.financial_period_id
    for share;

    if v_period_status is null then
      raise exception 'Financial period not found.' using errcode = 'P0002';
    end if;
    if v_period_status not in ('closed', 'locked') then
      raise exception 'Financial period must be closed or locked before publishing the report.'
        using errcode = '23514';
    end if;
    if v_period_end > current_date then
      raise exception 'Financial report cannot be published before the period end date (%).', v_period_end
        using errcode = '23514';
    end if;
  else
    raise exception 'Invalid financial report transition: % -> %', v_report.status, p_target
      using errcode = '42501';
  end if;

  if not app.has_permission(v_permission) then
    raise exception 'Missing permission: %', v_permission using errcode = '42501';
  end if;

  if p_target = 'review' then
    update public.financial_report_versions set status = 'review' where id = v_version.id;
    update public.financial_reports set status = 'review' where id = v_report.id;
  elsif p_target = 'approved' then
    update public.financial_report_versions
    set status = 'approved', approved_by = auth.uid(), approved_at = v_now
    where id = v_version.id;
    update public.financial_reports set status = 'approved' where id = v_report.id;
  elsif p_target = 'published' then
    update public.financial_report_versions
    set status = 'published', published_at = v_now
    where id = v_version.id;
    update public.financial_reports
    set status = 'published', published_version_id = v_version.id
    where id = v_report.id;
  end if;

  return query select v_report.id, v_version.id, v_report.status, p_target;
end;
$$;
