-- =============================================================================
-- Investors
--
-- Lifecycle, transition enforcement, append-only history, and the ownership
-- helpers every investor-facing policy is built on.
--
-- Mirrors src/core/investors/status.ts. A test asserts the two agree.
-- See docs/DATABASE.md §4.
-- =============================================================================

create type public.investor_status as enum (
  'prospective',
  'submitted',
  'under_review',
  'approved',
  'rejected',
  'active',
  'inactive'
);

create type public.investor_type as enum ('individual', 'institution');

create table public.investors (
  id uuid primary key references public.user_accounts (id) on delete cascade,

  -- Human-readable identifier used in correspondence. Generated by trigger.
  reference_code text not null unique,
  status public.investor_status not null default 'prospective',
  investor_type public.investor_type not null default 'individual',

  legal_name text not null,
  -- Identity numbers are stored hashed. If the plaintext is ever genuinely
  -- required it must use envelope encryption with a KMS-held key, not a column
  -- (docs/SECURITY.md §9).
  identity_number_hash text,

  country text not null default 'ID',
  city text,
  address text,

  organization_name text,
  organization_role text,

  application_note text,
  rejection_reason text,

  relationship_manager_id uuid references public.admins (id) on delete set null,

  applied_at timestamptz,
  reviewed_at timestamptz,
  reviewed_by uuid references public.admins (id) on delete set null,
  approved_at timestamptz,
  activated_at timestamptz,
  deactivated_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint investors_legal_name_not_blank check (length(btrim(legal_name)) > 0),
  constraint investors_country_iso check (country ~ '^[A-Z]{2}$'),
  constraint investors_institution_has_organization
    check (investor_type <> 'institution' or length(btrim(coalesce(organization_name, ''))) > 0),
  constraint investors_rejected_has_reason
    check (status <> 'rejected' or length(btrim(coalesce(rejection_reason, ''))) > 0)
);

create index investors_status_created_idx on public.investors (status, created_at desc);
create index investors_relationship_manager_idx
  on public.investors (relationship_manager_id) where relationship_manager_id is not null;
create index investors_legal_name_trgm_idx
  on public.investors using gin (legal_name extensions.gin_trgm_ops);

comment on table public.investors is
  'Investor records. Never hard-deleted — deactivated instead, so history survives.';

create trigger investors_set_updated_at
  before update on public.investors
  for each row execute function app.set_updated_at();

create trigger investors_reference_code_immutable
  before update on public.investors
  for each row execute function app.forbid_column_change('reference_code');

-- -----------------------------------------------------------------------------
-- Reference code: NTI-<year>-<zero-padded sequence>
-- -----------------------------------------------------------------------------
create sequence public.investor_reference_seq;

create or replace function app.assign_investor_reference()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.reference_code is null or length(btrim(new.reference_code)) = 0 then
    new.reference_code := 'NTI-'
      || to_char(now() at time zone 'UTC', 'YYYY')
      || '-'
      || lpad(nextval('public.investor_reference_seq')::text, 4, '0');
  end if;
  return new;
end;
$$;

create trigger investors_assign_reference
  before insert on public.investors
  for each row execute function app.assign_investor_reference();

create trigger investors_account_type_check
  before insert or update on public.investors
  for each row execute function app.assert_account_type('investor');

-- -----------------------------------------------------------------------------
-- Status history — append-only, written by trigger so it cannot be bypassed
-- -----------------------------------------------------------------------------
create table public.investor_status_history (
  id uuid primary key default gen_random_uuid(),
  investor_id uuid not null references public.investors (id) on delete cascade,
  from_status public.investor_status,
  to_status public.investor_status not null,
  changed_by uuid references public.user_accounts (id) on delete set null,
  -- Denormalised so the record stays readable after an account is removed.
  changed_by_label text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),

  constraint investor_status_history_metadata_object
    check (jsonb_typeof(metadata) = 'object')
);

create index investor_status_history_investor_idx
  on public.investor_status_history (investor_id, created_at desc);
-- Supports "what did this person change?" and keeps deleting an account from
-- scanning the whole table to null the reference.
create index investor_status_history_changed_by_idx
  on public.investor_status_history (changed_by) where changed_by is not null;

create trigger investor_status_history_append_only
  before update or delete on public.investor_status_history
  for each row execute function app.forbid_mutation();

comment on table public.investor_status_history is
  'Append-only lifecycle audit. Written by trigger on every status change.';

-- -----------------------------------------------------------------------------
-- Transition enforcement
--
-- The transition table is duplicated from src/core/investors/status.ts on
-- purpose: the application must not be the only thing standing between an
-- applicant and `active`. A test asserts the two tables agree.
-- -----------------------------------------------------------------------------
create or replace function app.investor_transition_allowed(
  p_from public.investor_status,
  p_to public.investor_status
)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select case p_from
    when 'prospective' then p_to = 'submitted'
    when 'submitted' then p_to in ('under_review', 'rejected')
    when 'under_review' then p_to in ('approved', 'rejected')
    when 'approved' then p_to in ('active', 'rejected')
    when 'active' then p_to = 'inactive'
    when 'inactive' then p_to = 'active'
    when 'rejected' then p_to = 'under_review'
    else false
  end;
$$;

-- Validation and timestamps run BEFORE the write, so an illegal transition is
-- rejected without touching the table.
create or replace function app.investor_status_validate()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' and new.status = old.status then
    return new;
  end if;

  if tg_op = 'UPDATE' and not app.investor_transition_allowed(old.status, new.status) then
    raise exception 'Investor status cannot move from % to %.', old.status, new.status
      using errcode = '23514';
  end if;

  -- Stamped by the database so they cannot disagree with the history rows or be
  -- back-dated by a client.
  if new.status = 'submitted' then new.applied_at := coalesce(new.applied_at, now()); end if;
  if new.status = 'under_review' then new.reviewed_at := now(); end if;
  if new.status = 'approved' then new.approved_at := now(); end if;
  if new.status = 'active' then new.activated_at := coalesce(new.activated_at, now()); end if;
  if new.status = 'inactive' then new.deactivated_at := now(); end if;

  return new;
end;
$$;

create trigger investors_status_validate
  before insert or update of status on public.investors
  for each row execute function app.investor_status_validate();

-- The history row is written AFTER the change, because on INSERT the investor
-- row does not exist yet and the history foreign key would have nothing to
-- point at.
create or replace function app.investor_status_record()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor uuid := (select auth.uid());
  actor_label text;
begin
  if tg_op = 'UPDATE' and new.status = old.status then
    return null;
  end if;

  select ua.full_name into actor_label from public.user_accounts ua where ua.id = actor;

  insert into public.investor_status_history
    (investor_id, from_status, to_status, changed_by, changed_by_label, reason)
  values (
    new.id,
    case when tg_op = 'UPDATE' then old.status else null end,
    new.status,
    actor,
    actor_label,
    case when new.status = 'rejected' then new.rejection_reason else null end
  );

  return null;
end;
$$;

create trigger investors_status_record
  after insert or update of status on public.investors
  for each row execute function app.investor_status_record();

-- =============================================================================
-- Ownership helpers
-- =============================================================================

-- NULL unless the caller is an investor whose status grants data access.
-- Every investor-scoped policy derives its row filter from this, so "which
-- investor am I" is answered once, from the session, and never from a request
-- parameter (docs/RBAC.md §5).
create or replace function app.current_investor_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select i.id
  from public.investors i
  join public.user_accounts ua on ua.id = i.id
  where i.id = (select auth.uid())
    and ua.status = 'active'
    and i.status in ('approved', 'active');
$$;

create or replace function app.is_investor()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.investors i where i.id = (select auth.uid())
  );
$$;

grant execute on function app.current_investor_id() to authenticated;
grant execute on function app.is_investor() to authenticated;
grant execute on function app.investor_transition_allowed(public.investor_status, public.investor_status)
  to authenticated;

comment on function app.current_investor_id() is
  'The calling investor''s id, but only while their status grants data access. NULL otherwise.';

-- =============================================================================
-- Privileges and RLS
-- =============================================================================

alter table public.investors enable row level security;
alter table public.investors force row level security;
alter table public.investor_status_history enable row level security;
alter table public.investor_status_history force row level security;

revoke all on public.investors from anon, authenticated;
revoke all on public.investor_status_history from anon, authenticated;

grant select on public.investors to authenticated;
grant update (
  legal_name, city, address, organization_name, organization_role, application_note
) on public.investors to authenticated;
grant select on public.investor_status_history to authenticated;

-- An investor reads their own record in any status, so a pending or rejected
-- applicant can still see where they stand.
create policy investors_select_self
  on public.investors for select to authenticated
  using (id = app.current_user_id());

create policy investors_select_admin
  on public.investors for select to authenticated
  using (app.has_permission('investors.view'));

-- An investor may correct their own details only while the application is still
-- theirs to edit. Once it is under review, changes go through an admin.
create policy investors_update_self
  on public.investors for update to authenticated
  using (id = app.current_user_id() and status in ('prospective', 'rejected'))
  with check (id = app.current_user_id() and status in ('prospective', 'rejected', 'submitted'));

create policy investors_update_admin
  on public.investors for update to authenticated
  using (app.has_permission('investors.update'))
  with check (app.has_permission('investors.update'));

-- No INSERT policy: investor records are created only by the application server
-- through the audited, rate-limited application flow.
-- No DELETE policy for anyone: investors are deactivated, never deleted.

create policy investor_status_history_select_self
  on public.investor_status_history for select to authenticated
  using (investor_id = app.current_user_id());

create policy investor_status_history_select_admin
  on public.investor_status_history for select to authenticated
  using (app.has_permission('investors.view'));

-- No INSERT/UPDATE/DELETE policy: rows are written only by the status trigger,
-- which runs as SECURITY DEFINER.
