-- System-generated business references
--
-- Internal business numbers must be generated by the database, not typed by
-- users or derived from a predictable sequence. Audit/version counters remain
-- sequential because their ordering is semantically meaningful.

create or replace function app.make_system_reference(
  p_prefix text,
  p_token_length integer default 10
)
returns text
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  clean_prefix text;
  token_length integer;
  random_token text;
begin
  clean_prefix := upper(regexp_replace(coalesce(p_prefix, 'REF'), '[^a-zA-Z0-9]+', '', 'g'));
  if clean_prefix = '' then
    clean_prefix := 'REF';
  end if;

  token_length := greatest(8, least(coalesce(p_token_length, 10), 20));
  random_token := upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, token_length));

  return clean_prefix
    || '-'
    || to_char(clock_timestamp() at time zone 'UTC', 'YYYYMMDD')
    || '-'
    || random_token;
end;
$$;

revoke all on function app.make_system_reference(text, integer) from public;
revoke all on function app.make_system_reference(text, integer) from anon;
revoke all on function app.make_system_reference(text, integer) from authenticated;

-- Investor reference numbers: replace the old sequential NTI-YYYY-0001 style
-- for newly-created investors while preserving all existing references.
create or replace function app.assign_investor_reference()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  candidate text;
  attempt integer;
begin
  if new.reference_code is null or length(btrim(new.reference_code)) = 0 then
    for attempt in 1..12 loop
      candidate := app.make_system_reference('NTI', 10);
      exit when not exists (
        select 1
        from public.investors i
        where i.reference_code = candidate
      );
    end loop;

    if candidate is null or exists (
      select 1 from public.investors i where i.reference_code = candidate
    ) then
      raise exception 'Unable to allocate a unique investor reference.'
        using errcode = '23505';
    end if;

    new.reference_code := candidate;
  end if;

  return new;
end;
$$;

revoke all on function app.assign_investor_reference() from public;
revoke all on function app.assign_investor_reference() from anon;
revoke all on function app.assign_investor_reference() from authenticated;

-- Meeting confirmation numbers are always assigned by the database. A caller
-- may omit the field entirely; any supplied value is intentionally replaced so
-- confirmation numbers remain system-owned.
create or replace function app.assign_meeting_confirmation_code()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  candidate text;
  attempt integer;
begin
  for attempt in 1..12 loop
    candidate := app.make_system_reference('MTG', 10);
    exit when not exists (
      select 1
      from public.meeting_bookings b
      where b.confirmation_code = candidate
    );
  end loop;

  if candidate is null or exists (
    select 1 from public.meeting_bookings b where b.confirmation_code = candidate
  ) then
    raise exception 'Unable to allocate a unique meeting confirmation code.'
      using errcode = '23505';
  end if;

  new.confirmation_code := candidate;
  return new;
end;
$$;

revoke all on function app.assign_meeting_confirmation_code() from public;
revoke all on function app.assign_meeting_confirmation_code() from anon;
revoke all on function app.assign_meeting_confirmation_code() from authenticated;

create unique index if not exists meeting_bookings_confirmation_code_uidx
  on public.meeting_bookings (confirmation_code);

drop trigger if exists meeting_bookings_assign_confirmation_code
  on public.meeting_bookings;

create trigger meeting_bookings_assign_confirmation_code
before insert on public.meeting_bookings
for each row
execute function app.assign_meeting_confirmation_code();

-- Ownership acquisition references are internal transaction references. Fill
-- legacy blanks once, then automatically allocate a random reference on every
-- new holding that does not already carry an explicit migration/import value.
create or replace function app.assign_ownership_acquisition_reference()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  candidate text;
  attempt integer;
begin
  if new.acquisition_reference is null or length(btrim(new.acquisition_reference)) = 0 then
    for attempt in 1..12 loop
      candidate := app.make_system_reference('OWN', 10);
      exit when not exists (
        select 1
        from public.ownership_holdings h
        where h.acquisition_reference = candidate
      );
    end loop;

    if candidate is null or exists (
      select 1 from public.ownership_holdings h where h.acquisition_reference = candidate
    ) then
      raise exception 'Unable to allocate a unique ownership acquisition reference.'
        using errcode = '23505';
    end if;

    new.acquisition_reference := candidate;
  end if;

  return new;
end;
$$;

revoke all on function app.assign_ownership_acquisition_reference() from public;
revoke all on function app.assign_ownership_acquisition_reference() from anon;
revoke all on function app.assign_ownership_acquisition_reference() from authenticated;

-- Backfill only blank legacy references. Existing business references are never
-- rewritten because they may already appear in signed documents or audit logs.
do $$
declare
  holding record;
  candidate text;
begin
  for holding in
    select id
    from public.ownership_holdings
    where acquisition_reference is null or length(btrim(acquisition_reference)) = 0
    for update
  loop
    loop
      candidate := app.make_system_reference('OWN', 10);
      exit when not exists (
        select 1
        from public.ownership_holdings h
        where h.acquisition_reference = candidate
      );
    end loop;

    update public.ownership_holdings
    set acquisition_reference = candidate
    where id = holding.id;
  end loop;
end;
$$;

create unique index if not exists ownership_holdings_acquisition_reference_uidx
  on public.ownership_holdings (acquisition_reference)
  where acquisition_reference is not null;

drop trigger if exists ownership_holdings_assign_acquisition_reference
  on public.ownership_holdings;

create trigger ownership_holdings_assign_acquisition_reference
before insert on public.ownership_holdings
for each row
execute function app.assign_ownership_acquisition_reference();

-- Future internal numbers (for example invoice, receipt, payout, agreement, or
-- inheritance references) must call app.make_system_reference with a stable
-- short prefix such as INV, RCP, PAY, AGR, or INH. External bank/provider
-- references and revision/version counters are intentionally excluded.
